Ensure requests to production fail

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -43,6 +43,17 @@ jobs:
             python-version: '3.9'
     steps:
       - uses: actions/checkout@v4
+      - name: Ensure requests to production domains fail
+        run: |
+          if [ "$NOT_LINUX" == "true" ] ; then
+            echo "Can't set /etc/hosts configuration on non-Linux runner"
+            exit 1
+          fi
+          echo "203.0.113.0 logfire.dev" | sudo tee -a /etc/hosts
+          echo "203.0.113.0 logfire-api.pydantic.dev" | sudo tee -a /etc/hosts
+          echo "203.0.113.0 logfire.pydantic.dev" | sudo tee -a /etc/hosts
+        env:
+          NOT_LINUX: runner.os != 'linux'
       - name: set up python
         uses: actions/setup-python@v5
         with:
